export const tasks = [
  { id: 1, title: 'Go to grossery', done: false },
  { id: 2, title: 'Buy a new charger', done: false },
  { id: 3, title: 'Call dad', done: false },
  { id: 4, title: 'Call mom', done: false },
  { id: 5, title: 'Work for two hours', done: false },
  { id: 6, title: 'Study React.Context API', done: false },
  { id: 7, title: 'Study MirageJS', done: false },
  { id: 8, title: 'Buy a new book', done: false },
  { id: 9, title: 'Read an article in english', done: false },
  { id: 10, title: 'Go to english class at 7:00pm', done: false },
  { id: 11, title: 'Pay the bills', done: false },
  { id: 12, title: "Write an article for the blog", done: false },
  { id: 13, title: 'Buy vodka', done: true },
];